/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ApiDecisionsRouteImport } from './routes/api.decisions'
import { Route as ApiReportsRouteImport } from './routes/api.reports'
import { Route as ApiStandingRouteImport } from './routes/api.standing'
import { Route as ApiStatusRouteImport } from './routes/api.status'
import { Route as ApiTriageRouteImport } from './routes/api.triage'
import { Route as ApiDocsIndexRouteImport } from './routes/api.docs.index'
import { Route as ApiFeedbackReportsRouteImport } from './routes/api.feedback.reports'
import { Route as ApiReportsIdRouteImport } from './routes/api.reports.$id'
import { Route as ApiStandingIdRouteImport } from './routes/api.standing.$id'
import { Route as ApiTriageResumeRouteImport } from './routes/api.triage.resume'
import { Route as ApiReportsIdArchiveRouteImport } from './routes/api.reports.$id.archive'
import { Route as ApiReportsIdDecideRouteImport } from './routes/api.reports.$id.decide'
import { Route as ApiReportsIdFeedbackRouteImport } from './routes/api.reports.$id.feedback'
import { Route as ApiReportsIdPendingRouteImport } from './routes/api.reports.$id.pending'
import { Route as ApiReportsIdRunRouteImport } from './routes/api.reports.$id.run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecisionsRoute = ApiDecisionsRouteImport.update({
  id: '/api/decisions',
  path: '/api/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStandingRoute = ApiStandingRouteImport.update({
  id: '/api/standing',
  path: '/api/standing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTriageRoute = ApiTriageRouteImport.update({
  id: '/api/triage',
  path: '/api/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsIndexRoute = ApiDocsIndexRouteImport.update({
  id: '/api/docs/',
  path: '/api/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackReportsRoute = ApiFeedbackReportsRouteImport.update({
  id: '/api/feedback/reports',
  path: '/api/feedback/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIdRoute = ApiReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiReportsRoute,
} as any)
const ApiStandingIdRoute = ApiStandingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStandingRoute,
} as any)
const ApiTriageResumeRoute = ApiTriageResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => ApiTriageRoute,
} as any)
const ApiReportsIdArchiveRoute = ApiReportsIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ApiReportsIdRoute,
} as any)
const ApiReportsIdDecideRoute = ApiReportsIdDecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => ApiReportsIdRoute,
} as any)
const ApiReportsIdFeedbackRoute = ApiReportsIdFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ApiReportsIdRoute,
} as any)
const ApiReportsIdPendingRoute = ApiReportsIdPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => ApiReportsIdRoute,
} as any)
const ApiReportsIdRunRoute = ApiReportsIdRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => ApiReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/memory': typeof MemoryRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/setup': typeof SetupRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/standing': typeof ApiStandingRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/api/triage': typeof ApiTriageRouteWithChildren
  '/api/feedback/reports': typeof ApiFeedbackReportsRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/standing/$id': typeof ApiStandingIdRoute
  '/api/triage/resume': typeof ApiTriageResumeRoute
  '/api/docs/': typeof ApiDocsIndexRoute
  '/api/reports/$id/archive': typeof ApiReportsIdArchiveRoute
  '/api/reports/$id/decide': typeof ApiReportsIdDecideRoute
  '/api/reports/$id/feedback': typeof ApiReportsIdFeedbackRoute
  '/api/reports/$id/pending': typeof ApiReportsIdPendingRoute
  '/api/reports/$id/run': typeof ApiReportsIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/memory': typeof MemoryRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/setup': typeof SetupRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/standing': typeof ApiStandingRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/api/triage': typeof ApiTriageRouteWithChildren
  '/api/feedback/reports': typeof ApiFeedbackReportsRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/standing/$id': typeof ApiStandingIdRoute
  '/api/triage/resume': typeof ApiTriageResumeRoute
  '/api/docs': typeof ApiDocsIndexRoute
  '/api/reports/$id/archive': typeof ApiReportsIdArchiveRoute
  '/api/reports/$id/decide': typeof ApiReportsIdDecideRoute
  '/api/reports/$id/feedback': typeof ApiReportsIdFeedbackRoute
  '/api/reports/$id/pending': typeof ApiReportsIdPendingRoute
  '/api/reports/$id/run': typeof ApiReportsIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/memory': typeof MemoryRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/setup': typeof SetupRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/standing': typeof ApiStandingRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/api/triage': typeof ApiTriageRouteWithChildren
  '/api/feedback/reports': typeof ApiFeedbackReportsRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/standing/$id': typeof ApiStandingIdRoute
  '/api/triage/resume': typeof ApiTriageResumeRoute
  '/api/docs/': typeof ApiDocsIndexRoute
  '/api/reports/$id/archive': typeof ApiReportsIdArchiveRoute
  '/api/reports/$id/decide': typeof ApiReportsIdDecideRoute
  '/api/reports/$id/feedback': typeof ApiReportsIdFeedbackRoute
  '/api/reports/$id/pending': typeof ApiReportsIdPendingRoute
  '/api/reports/$id/run': typeof ApiReportsIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decisions'
    | '/memory'
    | '/reports'
    | '/review'
    | '/setup'
    | '/api/decisions'
    | '/api/reports'
    | '/api/standing'
    | '/api/status'
    | '/api/triage'
    | '/api/feedback/reports'
    | '/api/reports/$id'
    | '/api/standing/$id'
    | '/api/triage/resume'
    | '/api/docs/'
    | '/api/reports/$id/archive'
    | '/api/reports/$id/decide'
    | '/api/reports/$id/feedback'
    | '/api/reports/$id/pending'
    | '/api/reports/$id/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decisions'
    | '/memory'
    | '/reports'
    | '/review'
    | '/setup'
    | '/api/decisions'
    | '/api/reports'
    | '/api/standing'
    | '/api/status'
    | '/api/triage'
    | '/api/feedback/reports'
    | '/api/reports/$id'
    | '/api/standing/$id'
    | '/api/triage/resume'
    | '/api/docs'
    | '/api/reports/$id/archive'
    | '/api/reports/$id/decide'
    | '/api/reports/$id/feedback'
    | '/api/reports/$id/pending'
    | '/api/reports/$id/run'
  id:
    | '__root__'
    | '/'
    | '/decisions'
    | '/memory'
    | '/reports'
    | '/review'
    | '/setup'
    | '/api/decisions'
    | '/api/reports'
    | '/api/standing'
    | '/api/status'
    | '/api/triage'
    | '/api/feedback/reports'
    | '/api/reports/$id'
    | '/api/standing/$id'
    | '/api/triage/resume'
    | '/api/docs/'
    | '/api/reports/$id/archive'
    | '/api/reports/$id/decide'
    | '/api/reports/$id/feedback'
    | '/api/reports/$id/pending'
    | '/api/reports/$id/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionsRoute: typeof DecisionsRoute
  MemoryRoute: typeof MemoryRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  SetupRoute: typeof SetupRoute
  ApiDecisionsRoute: typeof ApiDecisionsRoute
  ApiReportsRoute: typeof ApiReportsRouteWithChildren
  ApiStandingRoute: typeof ApiStandingRouteWithChildren
  ApiStatusRoute: typeof ApiStatusRoute
  ApiTriageRoute: typeof ApiTriageRouteWithChildren
  ApiFeedbackReportsRoute: typeof ApiFeedbackReportsRoute
  ApiDocsIndexRoute: typeof ApiDocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decisions': {
      id: '/api/decisions'
      path: '/api/decisions'
      fullPath: '/api/decisions'
      preLoaderRoute: typeof ApiDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/standing': {
      id: '/api/standing'
      path: '/api/standing'
      fullPath: '/api/standing'
      preLoaderRoute: typeof ApiStandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/triage': {
      id: '/api/triage'
      path: '/api/triage'
      fullPath: '/api/triage'
      preLoaderRoute: typeof ApiTriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/': {
      id: '/api/docs/'
      path: '/api/docs'
      fullPath: '/api/docs/'
      preLoaderRoute: typeof ApiDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback/reports': {
      id: '/api/feedback/reports'
      path: '/api/feedback/reports'
      fullPath: '/api/feedback/reports'
      preLoaderRoute: typeof ApiFeedbackReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id': {
      id: '/api/reports/$id'
      path: '/$id'
      fullPath: '/api/reports/$id'
      preLoaderRoute: typeof ApiReportsIdRouteImport
      parentRoute: typeof ApiReportsRoute
    }
    '/api/standing/$id': {
      id: '/api/standing/$id'
      path: '/$id'
      fullPath: '/api/standing/$id'
      preLoaderRoute: typeof ApiStandingIdRouteImport
      parentRoute: typeof ApiStandingRoute
    }
    '/api/triage/resume': {
      id: '/api/triage/resume'
      path: '/resume'
      fullPath: '/api/triage/resume'
      preLoaderRoute: typeof ApiTriageResumeRouteImport
      parentRoute: typeof ApiTriageRoute
    }
    '/api/reports/$id/archive': {
      id: '/api/reports/$id/archive'
      path: '/archive'
      fullPath: '/api/reports/$id/archive'
      preLoaderRoute: typeof ApiReportsIdArchiveRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
    '/api/reports/$id/decide': {
      id: '/api/reports/$id/decide'
      path: '/decide'
      fullPath: '/api/reports/$id/decide'
      preLoaderRoute: typeof ApiReportsIdDecideRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
    '/api/reports/$id/feedback': {
      id: '/api/reports/$id/feedback'
      path: '/feedback'
      fullPath: '/api/reports/$id/feedback'
      preLoaderRoute: typeof ApiReportsIdFeedbackRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
    '/api/reports/$id/pending': {
      id: '/api/reports/$id/pending'
      path: '/pending'
      fullPath: '/api/reports/$id/pending'
      preLoaderRoute: typeof ApiReportsIdPendingRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
    '/api/reports/$id/run': {
      id: '/api/reports/$id/run'
      path: '/run'
      fullPath: '/api/reports/$id/run'
      preLoaderRoute: typeof ApiReportsIdRunRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
  }
}

interface ApiReportsIdRouteChildren {
  ApiReportsIdArchiveRoute: typeof ApiReportsIdArchiveRoute
  ApiReportsIdDecideRoute: typeof ApiReportsIdDecideRoute
  ApiReportsIdFeedbackRoute: typeof ApiReportsIdFeedbackRoute
  ApiReportsIdPendingRoute: typeof ApiReportsIdPendingRoute
  ApiReportsIdRunRoute: typeof ApiReportsIdRunRoute
}

const ApiReportsIdRouteChildren: ApiReportsIdRouteChildren = {
  ApiReportsIdArchiveRoute: ApiReportsIdArchiveRoute,
  ApiReportsIdDecideRoute: ApiReportsIdDecideRoute,
  ApiReportsIdFeedbackRoute: ApiReportsIdFeedbackRoute,
  ApiReportsIdPendingRoute: ApiReportsIdPendingRoute,
  ApiReportsIdRunRoute: ApiReportsIdRunRoute,
}

const ApiReportsIdRouteWithChildren = ApiReportsIdRoute._addFileChildren(
  ApiReportsIdRouteChildren,
)

interface ApiReportsRouteChildren {
  ApiReportsIdRoute: typeof ApiReportsIdRouteWithChildren
}

const ApiReportsRouteChildren: ApiReportsRouteChildren = {
  ApiReportsIdRoute: ApiReportsIdRouteWithChildren,
}

const ApiReportsRouteWithChildren = ApiReportsRoute._addFileChildren(
  ApiReportsRouteChildren,
)

interface ApiStandingRouteChildren {
  ApiStandingIdRoute: typeof ApiStandingIdRoute
}

const ApiStandingRouteChildren: ApiStandingRouteChildren = {
  ApiStandingIdRoute: ApiStandingIdRoute,
}

const ApiStandingRouteWithChildren = ApiStandingRoute._addFileChildren(
  ApiStandingRouteChildren,
)

interface ApiTriageRouteChildren {
  ApiTriageResumeRoute: typeof ApiTriageResumeRoute
}

const ApiTriageRouteChildren: ApiTriageRouteChildren = {
  ApiTriageResumeRoute: ApiTriageResumeRoute,
}

const ApiTriageRouteWithChildren = ApiTriageRoute._addFileChildren(
  ApiTriageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionsRoute: DecisionsRoute,
  MemoryRoute: MemoryRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  SetupRoute: SetupRoute,
  ApiDecisionsRoute: ApiDecisionsRoute,
  ApiReportsRoute: ApiReportsRouteWithChildren,
  ApiStandingRoute: ApiStandingRouteWithChildren,
  ApiStatusRoute: ApiStatusRoute,
  ApiTriageRoute: ApiTriageRouteWithChildren,
  ApiFeedbackReportsRoute: ApiFeedbackReportsRoute,
  ApiDocsIndexRoute: ApiDocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
